### ISSUE TITLE
Can't join videos on Android 11 (writeSampleData returned an error)

### ISSUE THREAD

**Issue by maff91** [natario1/Transcoder#107]
### Issue

When joining videos on Android 11 the transcoding fails at the last buffer of the first video.
The code works perfectly fine on Android 10.

### Test case

Reproduces in the demo app, here used the same file twice in order to ensure the resolution and format of the inputs is the same.

```
mTranscodeFuture = Transcoder.into(sink)
        .setListener(this)
        .addDataSource(this, mTranscodeInputUri1)
        .addDataSource(this, mTranscodeInputUri1)
        .transcode();
```

### Error

```
2020-11-05 00:37:20.706 12399-12471/com.otaliastudios.transcoder.demo E/MediaAdapter: pushBuffer called before start
2020-11-05 00:37:20.715 12399-12471/com.otaliastudios.transcoder.demo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x0
```
...
```
2020-11-05 00:37:20.754 12399-12471/com.otaliastudios.transcoder.demo E/Transcoder: Fatal error while transcoding, this might be invalid format or bug in engine or Android.
    java.lang.IllegalStateException: writeSampleData returned an error
        at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:722)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.writeTrack(DefaultDataSink.java:151)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.drainEncoder(BaseTrackTranscoder.java:288)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.transcode(BaseTrackTranscoder.java:163)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:376)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:150)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:140)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by tburt** [comment]
We've also encountered this issue on all our Android 11 test devices.

**Comment by maff91** [comment]
@tburt We ended up forking the repository and fixing the problem ourselves. FYI, I opened a PR #108, but there was no response from the maintainer so far.

**Comment by tburt** [comment]
@maff91, thanks very much for the info, and thanks for investigating and sharing your results... will save us a lot of time. I'll contact maintainer too and see if we can find status of project.

**Comment by natario1** [comment]
I had no time to review the issue, I can say that there are two things I don't like about the PR:
- It won't send the last EOS to the muxer. That might be needed for file integrity or resources cleanup.
- It only fixes `DefaultDataSink`. Other sink implementation will have to remember about this weird detail.

My opinion is that the sinks should not receive this buffer in the first place. A good solution could be to create a data sink wrapper that implements `DataSink`:

```kotlin
class SegmentDataSink(private val realDataSink: DataSink, private val isLastSegment: Boolean) : DataSink {
    // Delegate all calls to realDataSink, but if we're not the last segment, do not delegate EOS!
}
```

It's in kotlin but you get the point. The `Engine` class could create one of these for each `TrackTranscoder` and pass it to the transcoder constructor instead of the real DataSink. This is just a possible solution, that avoids adding the fix to all sinks or all transcoders, and it sends the last EOS. Thanks for your involvement @maff91 !

**Comment by maff91** [comment]
@natario1 Thank you for the feedback. I just force-pushed a different solution addressing your points. Yeah, not passing the empty buffers to the data sink at all looks better, especially considering they are created by code and not coming from the decoder.

Please take a look, I hope this change should not break any logic in the `DefaultDataSink`.

**Comment by tburt** [comment]
Thanks @maff91... @natario1 do you think you'll have a chance to review this at some point?
