### ISSUE TITLE
NullPointerException with ClipDataSource(FilePathDataSource())

### ISSUE THREAD

**Issue by DamonChen117** [natario1/Transcoder#133]
Version:0.10.2

Code:
```
val builder = Transcoder.into(trimmedFile.path)
builder.addDataSource(ClipDataSource(FilePathDataSource(outputFile.path), startTime , endTime))
```

It seems caused by FilePathDataSource.initialize doesn't call super.initialize.
                
Exception:
**java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.media.MediaMetadataRetriever.extractMetadata(int)' on a null object reference
at com.otaliastudios.transcoder.source.DefaultDataSource.getDurationUs(DefaultDataSource.java:276)
at com.otaliastudios.transcoder.source.ClipDataSource.getSourceDurationUs(ClipDataSource.java:23)
at com.otaliastudios.transcoder.source.ClipDataSource.<init>(ClipDataSource.java:18)**

**Comment by natario1** [comment]
Thanks! Can you fix this? You could also look at deinitialize() (super call is needed!) and other sources.
