### ISSUE TITLE
Latest version -0.10.3 Issue in Multiple  Video File(Mp4) and Audio File(Mp3) Merging Issue

### ISSUE THREAD

**Issue by manishmips28** [natario1/Transcoder#144]
Hi 

I was using 0.9.1 for a while and there was not any problem I have updated my android device to 11 

Multiple file merging issue was there in android 11 only it is working below 11 

Now I have updated 0.10.3 Now there is issue with Video File and Audio File merging .

Error 

```
TranscodeEngine: Unexpected error while transcoding.
    java.lang.IllegalArgumentException: Failed requirement.
        at com.otaliastudios.transcoder.internal.audio.ChunkQueue.enqueue(chunks.kt:28)
        at com.otaliastudios.transcoder.internal.audio.AudioEngine.enqueue(AudioEngine.kt:59)
        at com.otaliastudios.transcoder.internal.audio.AudioEngine.enqueue(AudioEngine.kt:21)
        at com.otaliastudios.transcoder.internal.pipeline.QueuedStep.step(steps.kt:40)
        at com.otaliastudios.transcoder.internal.pipeline.Pipeline.executeStep(Pipeline.kt:51)
        at com.otaliastudios.transcoder.internal.pipeline.Pipeline.execute(Pipeline.kt:28)
        at com.otaliastudios.transcoder.internal.Segment.advance(Segment.kt:18)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:114)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

Exception onError
`onTranscodeFailed exception:Failed requirement.`

and also `TranscodeEngine: Unexpected error while transcoding.
    java.lang.IllegalArgumentException: bufferInfo must specify a valid buffer offset, size and presentation time
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:682)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.writeTrack(DefaultDataSink.java:163)
        at com.otaliastudios.transcoder.internal.utils.EosIgnoringDataSink.writeTrack(eos.kt:28)
        at com.otaliastudios.transcoder.internal.data.Writer.step(Writer.kt:50)
        at com.otaliastudios.transcoder.internal.pipeline.Pipeline.executeStep(Pipeline.kt:51)
        at com.otaliastudios.transcoder.internal.pipeline.Pipeline.execute(Pipeline.kt:28)
        at com.otaliastudios.transcoder.internal.Segment.advance(Segment.kt:18)
        at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.transcode(DefaultTranscodeEngine.kt:114)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:48)
        at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
`

**Comment by SunyChoudhary** [comment]
I am alsso getting the same issue.

**Comment by manishmips28** [comment]
I had used  two version of same lib for resolving this .

**Comment by mikewalkerjr** [comment]
I'm getting the same issue with certain devices
