### ISSUE TITLE
Fatal exception in DefaultAudioStrategy on video without audio

### ISSUE THREAD

**Issue by pawegio** [natario1/Transcoder#28]
When I try to transcode video without audio track fatal exception is thrown:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
       at android.media.MediaFormat.getInteger + 998(MediaFormat.java:998)
       at com.otaliastudios.transcoder.strategy.DefaultAudioStrategy.getInputChannelCount + 115(DefaultAudioStrategy.java:115)
       at com.otaliastudios.transcoder.strategy.DefaultAudioStrategy.createOutputFormat + 100(DefaultAudioStrategy.java:100)
       at com.otaliastudios.transcoder.engine.Engine.computeTrackStatus + 126(Engine.java:126)
       at com.otaliastudios.transcoder.engine.Engine.transcode + 322(Engine.java:322)
       at com.otaliastudios.transcoder.Transcoder$1.call + 134(Transcoder.java:134)
       at com.otaliastudios.transcoder.Transcoder$1.call + 124(Transcoder.java:124)
       at java.util.concurrent.FutureTask.run + 266(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1167(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run + 764(Thread.java:764)
```

I use single parameter `addDataSource` function without specifying `TrackType` so I expected audio track to be ignored when it's not included in the input file.

**Comment by pawegio** [comment]
only workaround for me is applying in the builder:

```kotlin
setAudioTrackStrategy(
    if (file.hasAudioTrack) {
        DefaultAudioStrategy.Builder().build()
    } else {
        RemoveTrackStrategy()
    }
)
```

where `hasAudioTrack` is extension function defined:

```kotlin
private val File.hasAudioTrack: Boolean
    get() {
        val hasAudioMetadata = MediaMetadataRetriever().apply {
            setDataSource(absolutePath)
        }.extractMetadata(MediaMetadataRetriever.METADATA_KEY_HAS_AUDIO)
        return hasAudioMetadata != null && hasAudioMetadata == "yes"
    }
```

**Comment by natario1** [comment]
@pawegio what is the value of `hasAudioMetadata` in your case? null, or just something different than `yes`?

**Comment by pawegio** [comment]
the value is `null`

**Comment by natario1** [comment]
I see. I'm not sure if we can trust that all files that **have** audio will have this key set.

Could you send here your file?

**Comment by pawegio** [comment]
Unfortunately, I can't send you the file, but I can share with you `MediaFormat` map value passed to `decodeMediaFormat()` for type `AUDIO`:
```
{track-id=1, level=512, mime=video/avc, frame-count=114, profile=1, language=```, display-width=1088, csd-1=java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], durationUs=5700000, display-height=512, width=1088, rotation-degrees=90, max-input-size=84261, frame-rate=20, height=512, csd-0=java.nio.HeapByteBuffer[pos=0 lim=13 cap=13]}
```

Btw. after updating to 0.7.2 (and without my workaround), the call stack for exception is now:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
    at com.otaliastudios.transcoder.source.DefaultDataSource.selectTrack(DefaultDataSource.java:62)
    at com.otaliastudios.transcoder.engine.MediaFormatProvider.decodeMediaFormat(MediaFormatProvider.java:87)
    at com.otaliastudios.transcoder.engine.MediaFormatProvider.provideMediaFormat(MediaFormatProvider.java:42)
    at com.otaliastudios.transcoder.engine.Engine.computeTrackStatus(Engine.java:121)
    at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:323)
    at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
    at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```

**Comment by pawegio** [comment]
In **0.7.2** my workaround no longer works...

**Comment by natario1** [comment]
I'd like to see the `MediaFormat` map that is passed as an input format to `DefaultAudioStrategy` in 0.7.1.

About 0.7.2, not sure why you are getting a video format for type=AUDIO, but we can investigate this later.

**Comment by pawegio** [comment]
0.7.1:

`DefaultAudioStrategy.createOutputFormat`

input media format:
```
{track-id=1, level=512, mime=video/avc, frame-count=114, profile=1, language=```, display-width=1088, csd-1=java.nio.HeapByteBuffer[pos=0 lim=8 cap=8], durationUs=5700000, display-height=512, width=1088, rotation-degrees=90, max-input-size=84261, frame-rate=20, height=512, csd-0=java.nio.HeapByteBuffer[pos=0 lim=13 cap=13]}
```

so it's video format as well.

I think the problem is with `DefaultDataSource.getTrackFormat` function that returns video format instead of `null`.

```java
@Nullable
@Override
public MediaFormat getTrackFormat(@NonNull TrackType type) {
    if (mFormats.has(type)) return mFormats.get(type);
    ensureExtractor();
    int trackCount = mExtractor.getTrackCount();
    MediaFormat format = null;
    for (int i = 0; i < trackCount; i++) {
        format = mExtractor.getTrackFormat(i); <-- Is it correct to assign value here?
        String mime = format.getString(MediaFormat.KEY_MIME);
        if (type == TrackType.VIDEO && mime.startsWith("video/")) {
            mIndex.set(TrackType.VIDEO, i);
            break;
        }
        if (type == TrackType.AUDIO && mime.startsWith("audio/")) {
            mIndex.set(TrackType.AUDIO, i);
            break;
        }
    }
    mFormats.set(type, format);
    return format;
}
```

**Comment by natario1** [comment]
Ah, that's correct ! Would you like to set up a PR?

**Comment by joeShuff** [comment]
In version `0.7.3` I am still getting the same issue with a file that doesn't have an audio track. Stack Trace: 
`    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.otaliastudios.transcoder.source.DefaultDataSource.selectTrack(DefaultDataSource.java:62)
        at com.otaliastudios.transcoder.engine.Engine.openCurrentStep(Engine.java:149)
        at com.otaliastudios.transcoder.engine.Engine.getCurrentTrackTranscoder(Engine.java:219)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:368)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

I am simply calling
`builder.addDataSource(filePath)` 

I am not sure whether the documentation is just not complete for the new fix or not?

I implemented your `hasAudioTrack` method and that is correctly reporting that the file I have doesn't have an audio track.

Any help is appreciated. Feel free to ask for more info

**Comment by nzackoya** [comment]
@joeShuff you're right it is still happening, you can try the workaround below for now

val transcoder = Transcoder.into(toPath)
      .addDataSource(TrackType.VIDEO, source)
      .setListener(transcoderListener)

    if (source.getTrackFormat(TrackType.AUDIO) != null) {
      transcoder.addDataSource(TrackType.AUDIO, source)
    }
    transcoder.transcode()
