### ISSUE TITLE
Does it work on Android Q devices?

### ISSUE THREAD

**Issue by LutfiTekin** [natario1/Transcoder#42]
Hi there I've been trying in on an emulator running android q and I got this following error.

`Fatal error while transcoding, this might be invalid format or bug in engine or Android.
    java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1864)
        at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1827)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.setUp(BaseTrackTranscoder.java:59)
        at com.otaliastudios.transcoder.engine.Engine.openCurrentStep(Engine.java:190)
        at com.otaliastudios.transcoder.engine.Engine.getCurrentTrackTranscoder(Engine.java:219)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:371)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

It happens only in API 29

**Comment by natario1** [comment]
There is nothing in Android Q that would make this break as far as I know. I would suggest trying with a real device

**Comment by LutfiTekin** [comment]
Ok thanks,
 I have Huawei mate 20 and waiting for Android Q update will let you know then.

**Comment by LutfiTekin** [comment]
I can confirm it works on a real device.

**Comment by aweck** [comment]
Also works fine on my Android Q device
