### ISSUE TITLE
Error 0xffffec77

### ISSUE THREAD

**Issue by themadmrj** [natario1/Transcoder#43]
Somehow I constantly get the following error 0xffffec77 on multiple devices (Samsung + Xaomi). Min SDK is 21. Any idea what might cause it? Even when I keep my config to defaults:

```
                val mTranscodeVideoStrategy = DefaultVideoStrategy.Builder()
                    .bitRate(TARGET_VIDEO_BITRATE.toLong())
                    //.addResizer(if (aspectRatio > 0) AspectRatioResizer(aspectRatio) else PassThroughResizer())
                    //.addResizer(AtMostResizer(TARGET_VIDEO_HEIGHT))
                    //.addResizer(ExactResizer(Size(TARGET_VIDEO_WIDTH, TARGET_VIDEO_HEIGHT)))
                    .build()

                val future = Transcoder
                    .into(compressedFilePath)
                    .setVideoTrackStrategy(mTranscodeVideoStrategy)
                    .addDataSource(sourceFilePath)
                    .setListener(this).transcode()
                future.get()
```
The video is perfectly playable and all permissions are given.
I suspect this line to be the cause:
`2019-11-16 11:32:40.513 32514-1162/com.clash.android.debug E/ACodec:  configureCodec multi window instance fail  appPid : 32514`
Does that mean that the codec is already used somewhere? But that may not even be by the same app? I tried transcoding a video file that's never actually played by any MediaPlayer or even loaded as a image by Glide, same result.
Here is the stacktrace:

```
[2019-11-16 11:13:15.836 26907-28900/com.test.android.debug D/CompressFileWorker: start compressing
2019-11-16 11:13:15.857 26907-28901/com.test.android.debug W/FileSource: offset/length adjusted from 0/576460752303423487 to 0/4206980
2019-11-16 11:13:15.888 26907-28901/com.test.android.debug I/DefaultVideoStrategy: Input width&height: 1920x1080
2019-11-16 11:13:15.888 26907-28901/com.test.android.debug I/DefaultVideoStrategy: Output width&height: 1920x1080
2019-11-16 11:13:15.890 26907-28901/com.test.android.debug V/Engine: Duration (us): 11609000
2019-11-16 11:13:15.890 26907-28901/com.test.android.debug V/Engine: new step: 0
2019-11-16 11:13:15.894 26907-28901/com.test.android.debug I/ACodec:  [] Now uninitialized
2019-11-16 11:13:15.895 26907-28902/com.test.android.debug I/ACodec: [] onAllocateComponent
2019-11-16 11:13:15.896 26907-28902/com.test.android.debug I/OMXClient: MuxOMX ctor
2019-11-16 11:13:15.896 26907-28902/com.test.android.debug I/ACodec: Set Google AAC Dec for aacProfile 0
2019-11-16 11:13:15.906 26907-28902/com.test.android.debug I/ACodec: [OMX.google.aac.encoder] Now Loaded
2019-11-16 11:13:15.909 26907-28902/com.test.android.debug I/ACodec: [OMX.google.aac.encoder] Now Loaded->Idle
2019-11-16 11:13:15.912 26907-28902/com.test.android.debug I/ACodec: [OMX.google.aac.encoder] Now Idle->Executing
2019-11-16 11:13:15.913 26907-28902/com.test.android.debug I/ACodec: [OMX.google.aac.encoder] Now Executing
2019-11-16 11:13:15.914 26907-28901/com.test.android.debug I/ACodec:  [] Now uninitialized
2019-11-16 11:13:15.915 26907-28905/com.test.android.debug I/ACodec: [] onAllocateComponent
2019-11-16 11:13:15.916 26907-28905/com.test.android.debug I/OMXClient: MuxOMX ctor
2019-11-16 11:13:15.916 26907-28905/com.test.android.debug I/ACodec: Set Google AAC Dec for aacProfile 0
2019-11-16 11:13:15.924 26907-28905/com.test.android.debug I/ACodec: [OMX.google.aac.decoder] Now Loaded
2019-11-16 11:13:15.927 26907-28905/com.test.android.debug I/ACodec: [OMX.google.aac.decoder] Now Loaded->Idle
2019-11-16 11:13:15.931 26907-28905/com.test.android.debug I/ACodec: [OMX.google.aac.decoder] Now Idle->Executing
2019-11-16 11:13:15.932 26907-28905/com.test.android.debug I/ACodec: [OMX.google.aac.decoder] Now Executing
2019-11-16 11:13:15.936 26907-28905/com.test.android.debug I/ACodec: [OMX.google.aac.decoder] Now handling output port settings change
2019-11-16 11:13:15.940 26907-28905/com.test.android.debug I/ACodec: [OMX.google.aac.decoder] Now Executing
2019-11-16 11:13:15.949 26907-28901/com.test.android.debug I/ACodec:  [] Now uninitialized
2019-11-16 11:13:15.950 26907-28909/com.test.android.debug I/ACodec: [] onAllocateComponent
2019-11-16 11:13:15.951 26907-28909/com.test.android.debug I/OMXClient: MuxOMX ctor
2019-11-16 11:13:15.951 26907-28909/com.test.android.debug I/ACodec: Set Google AAC Dec for aacProfile 0
2019-11-16 11:13:15.985 26907-28909/com.test.android.debug I/ACodec: [OMX.Exynos.AVC.Encoder] Now Loaded
2019-11-16 11:13:15.990 26907-28909/com.test.android.debug W/ACodec: do not know color format 0x7f000011 = 2130706449
2019-11-16 11:13:15.991 26907-28909/com.test.android.debug W/ACodec: do not know color format 0x10 = 16
2019-11-16 11:13:15.991 26907-28909/com.test.android.debug W/ACodec: do not know color format 0x7f00a000 = 2130747392
2019-11-16 11:13:15.992 26907-28909/com.test.android.debug W/ACodec: do not know color format 0x7f000789 = 2130708361
2019-11-16 11:13:15.996 26907-28909/com.test.android.debug I/ACodec: setupAVCEncoderParameters with [profile: Baseline] [level: Level1]
2019-11-16 11:13:15.997 26907-28909/com.test.android.debug I/ACodec: Enable perceptual video coding
2019-11-16 11:13:15.997 26907-28909/com.test.android.debug I/ACodec: Success set VideoMinQP(5/5/5) VideoMaxQP(50/50/50)
2019-11-16 11:13:15.999 26907-28909/com.test.android.debug I/ACodec: [OMX.Exynos.AVC.Encoder] cannot encode HDR static metadata. Ignoring.
2019-11-16 11:13:15.999 26907-28909/com.test.android.debug I/ACodec: setupVideoEncoder succeeded
2019-11-16 11:13:16.000 26907-28909/com.test.android.debug W/ACodec: do not know color format 0x7f000789 = 2130708361
2019-11-16 11:13:16.011 26907-28901/com.test.android.debug D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1920x1080]-format:1
2019-11-16 11:13:16.013 26907-28909/com.test.android.debug I/ACodec: [OMX.Exynos.AVC.Encoder] Now Loaded->Idle
2019-11-16 11:13:16.034 26907-28901/com.test.android.debug I/ACodec:  [] Now uninitialized
2019-11-16 11:13:16.052 26907-28921/com.test.android.debug I/ACodec: [] onAllocateComponent
2019-11-16 11:13:16.054 26907-28909/com.test.android.debug I/ACodec: [OMX.Exynos.AVC.Encoder] Now Idle->Executing
2019-11-16 11:13:16.054 26907-28921/com.test.android.debug I/OMXClient: MuxOMX ctor
2019-11-16 11:13:16.054 26907-28921/com.test.android.debug I/ACodec: Set Google AAC Dec for aacProfile 0
2019-11-16 11:13:16.056 26907-28909/com.test.android.debug I/ACodec: [OMX.Exynos.AVC.Encoder] Now Executing
2019-11-16 11:13:16.063 26907-28921/com.test.android.debug I/ACodec: [OMX.Exynos.avc.dec] Now Loaded
2019-11-16 11:13:16.070 26907-28918/com.test.android.debug I/MediaCodec: [OMX.Exynos.avc.dec] setting surface generation to 27552774
2019-11-16 11:13:16.071 26907-28921/com.test.android.debug I/ACodec: can't find wfdsink-exynos-enable
2019-11-16 11:13:16.075 26907-28921/com.test.android.debug E/ACodec:  configureCodec multi window instance fail  appPid : 26907
2019-11-16 11:13:16.076 26907-28921/com.test.android.debug E/ACodec: [OMX.Exynos.avc.dec] configureCodec returning error -5001
2019-11-16 11:13:16.077 26907-28921/com.test.android.debug E/ACodec: signalError(omxError 0x80001001, internalError -5001)
2019-11-16 11:13:16.077 26907-28918/com.test.android.debug E/MediaCodec: Codec reported err 0xffffec77, actionCode 0, while in state 3
2019-11-16 11:13:16.077 26907-28901/com.test.android.debug E/MediaCodec: configure failed with err 0xffffec77, resetting...
2019-11-16 11:13:16.080 26907-28921/com.test.android.debug I/ACodec:  [OMX.Exynos.avc.dec] Now uninitialized
2019-11-16 11:13:16.080 26907-28921/com.test.android.debug I/ACodec:  [] Now kWhatShutdownCompleted event : 8554
2019-11-16 11:13:16.080 26907-28918/com.test.android.debug I/MediaCodec: Codec shutdown complete
2019-11-16 11:13:16.081 26907-28901/com.test.android.debug I/ACodec:  [] Now uninitialized
2019-11-16 11:13:16.081 26907-28921/com.test.android.debug I/ACodec: [] onAllocateComponent
2019-11-16 11:13:16.083 26907-28921/com.test.android.debug I/OMXClient: MuxOMX ctor
2019-11-16 11:13:16.083 26907-28921/com.test.android.debug I/ACodec: Set Google AAC Dec for aacProfile 0
2019-11-16 11:13:16.090 26907-28921/com.test.android.debug I/ACodec: [OMX.Exynos.avc.dec] Now Loaded
2019-11-16 11:13:16.092 26907-28901/com.test.android.debug E/Transcoder: Fatal error while transcoding, this might be invalid format or bug in engine or Android.
    android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1882)
        at com.otaliastudios.transcoder.transcode.VideoTrackTranscoder.onConfigureDecoder(VideoTrackTranscoder.java:105)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.setUp(BaseTrackTranscoder.java:75)
        at com.otaliastudios.transcoder.engine.Engine.openCurrentStep(Engine.java:190)
        at com.otaliastudios.transcoder.engine.Engine.getCurrentTrackTranscoder(Engine.java:219)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:371)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)](url)
```

**Comment by themadmrj** [comment]
After many hours of testing, it appears the problem was linked to the WorkManager.
I previously had my transcoding workers run in parallel, which I now changed to run sequentially and it seems to have fixed my issue.
The wierd part is, that in order to debug I tried transcoding a single video file and it still didn't work. My only guess is that since I have 2 versions of the same app on my device (debug+release), perhaps by crashing both versions on the codec part, the codec couldn't be released properly. It got fixed after restarting the device. Topic can be closed and for future references, be careful with the WorkManager, I still have some strange behaviour!
