### ISSUE TITLE
Exception transcoding avi on Vivo y81i android 8.1

### ISSUE THREAD

**Issue by nzackoya** [natario1/Transcoder#60]
DefaultDataSink: Failed to release the muxer.
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:457)
        at android.media.MediaMuxer.release(MediaMuxer.java:696)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.release(DefaultDataSink.java:189)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:390)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Transcoder: Fatal error while transcoding, this might be invalid format or bug in engine or Android.
    java.lang.IllegalStateException: writeSampleData returned an error
        at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:684)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.writeTrack(DefaultDataSink.java:134)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.drainEncoder(BaseTrackTranscoder.java:288)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.transcode(BaseTrackTranscoder.java:163)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:369)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
VideosKt$cutVideoTo15Seconds: java.lang.IllegalStateException: writeSampleData returned an error
        at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:684)
        at com.otaliastudios.transcoder.sink.DefaultDataSink.writeTrack(DefaultDataSink.java:134)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.drainEncoder(BaseTrackTranscoder.java:288)
        at com.otaliastudios.transcoder.transcode.BaseTrackTranscoder.transcode(BaseTrackTranscoder.java:163)
        at com.otaliastudios.transcoder.engine.Engine.transcode(Engine.java:369)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:134)
        at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:124)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by nzackoya** [comment]
What is better in this library if you just copied from ypresto transcoder with all the bugs it has and you even don't look at the issues that seems copy of ypresto transcoder
